### ISSUE TITLE
Problem css 

### ISSUE THREAD

**Issue by Lokdi** [magma-app/magma-widget#16]
Hello, 
why did you add this code into css CDN ? it impacts the whole site, the before as well as the after ? 

```
*,*:before,*:after {
    box-sizing: border-box;
    margin: 0;
    font-weight: 400
}
```

**Comment by jorisrenaud** [comment]
Thanks a lot @Lokdi for pointing this out! We gonna fix it today.

**Comment by hugoLarrousse** [comment]
Hello @Lokdi,
Thank you for reporting the problem. It has now been resolved.
You may need to refresh the cache to get the latest version.
